# Generated by Django 4.2.1 on 2023-08-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OKDK', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signal',
            old_name='staus',
            new_name='status',
        ),
    ]
