# Generated by Django 4.2.1 on 2023-05-23 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='menu')),
                ('price', models.IntegerField()),
                ('category_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category1')),
                ('category_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category2')),
                ('category_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category3')),
            ],
        ),
    ]
