# Generated by Django 4.2.1 on 2023-05-23 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_menu_category_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='category_1',
        ),
    ]
