# Generated by Django 4.2.1 on 2023-05-23 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_category1_type'),
        ('menu', '0003_remove_menu_category_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.category1'),
            preserve_default=False,
        ),
    ]
