# Generated by Django 4.2.1 on 2023-05-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_pack',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
