# Generated by Django 4.2.1 on 2023-07-27 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_menu_category_1'),
        ('order', '0003_alter_order_is_pack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='menu',
        ),
        migrations.AddField(
            model_name='option',
            name='menu',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='menu.menu'),
            preserve_default=False,
        ),
    ]
